log:
  level: 0
  file: './logs/api.log'
  max-size: 100
  max-backups: 30
  max-age: 15
  compress: true
  service-name: 'os'

system:
  addr: 8080
  static-dir: './public'
  mode: 'debug'
  db-type: 'mysql'
  encryption-cost: 12

mysql:
  db-name: 'os'
  addr: '127.0.0.1:3306'
  username: 'root'
  password: ''
  max-idle-conns: 50
  max-open-conns: 200
  max-life-time: 5
  log-mode: true

redis:
  network: 'tcp'
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

jwt:
  signing-key: 'jwt_test'
test: 'bdds'
