log:
  level: 0
  file: './logs/api.log'
  max_size: 100
  max_backups: 30
  max_age: 15
  compress: true
  service_name: 'os'

system:
  addr: 8080
  static_dir: './public'
  mode: 'debug'
  db-type: 'mysql'

mysql:
  db-name: 'os'
  addr: '127.0.0.1:3306'
  username: 'root'
  password: '123456'
  max-idle-conns: 50
  max-open-conns: 200
  max_life_time: 5
  log-mode: true

redis:
  network: 'tcp'
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

jwt:
  signing-key: 'jwt_test'
test: 'bdds'
