basePath: /api/v1
definitions:
  Captcha:
    properties:
      phone:
        type: string
    required:
    - phone
    type: object
  Login:
    properties:
      code:
        description: 验证码
        type: integer
      passwrod:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
    required:
    - phone
    type: object
  Register:
    properties:
      code:
        description: 验证码
        type: string
      nickname:
        description: 用户昵称
        type: string
      passwrod:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
    required:
    - code
    - passwrod
    - phone
    type: object
  Response:
    properties:
      code:
        description: Code
        type: integer
      data:
        description: Data
        type: object
      msg:
        description: Message
        type: string
    type: object
  model.User:
    properties:
      created_at:
        type: string
      headerImg:
        description: 头像
        type: string
      id:
        description: 用户id
        type: integer
      nickName:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  resource.SysLoginResource:
    properties:
      token:
        type: string
    type: object
  resource.SysUserResource:
    properties:
      user:
        $ref: '#/definitions/model.User'
    type: object
host: localhost:8080
info:
  contact:
    email: zhangbiao19931203@gmail.com
    name: OS API
  description: This is a sample server celler server.
  title: OS Example API
  version: "1.0"
paths:
  /base/captcha:
    post:
      consumes:
      - application/json
      parameters:
      - description: param
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Captcha'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Response'
      summary: 发送验证码
      tags:
      - Base
  /base/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: param
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                data:
                  $ref: '#/definitions/resource.SysLoginResource'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
      summary: 用户登录
      tags:
      - Base
  /base/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: param
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                data:
                  $ref: '#/definitions/resource.SysUserResource'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response'
      summary: 用户注册账号
      tags:
      - Base
  /user/me:
    post:
      consumes:
      - application/json
      description: 获取用户信息接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                data:
                  $ref: '#/definitions/resource.SysUserResource'
              type: object
        "400":
          description: +
          schema:
            $ref: '#/definitions/Response'
      security:
      - JWT: []
      summary: 用户信息
      tags:
      - user
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
