basePath: /api/v1
definitions:
  model.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      nickName:
        type: string
      phone:
        type: string
      uuid:
        type: string
    type: object
  resource.SysUserResource:
    properties:
      user:
        $ref: '#/definitions/model.User'
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  service.RegisterStruct:
    properties:
      nickname:
        type: string
      passwrod:
        type: string
      phone:
        type: string
    required:
    - passwrod
    - phone
    type: object
host: localhost:8080
info:
  contact:
    email: zhangbiao19931203@gmail.com
    name: OS API
  description: This is a sample server celler server.
  title: OS Example API
  version: "1.0"
paths:
  /base/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: param
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.RegisterStruct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/resource.SysUserResource'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户注册账号
      tags:
      - Base
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
