logger:
  level: 0
  # 日志存放路径
  path: 'temp/logs'
  # 日志文件大小
  max-size: 1
  # 日志保留数量
  max-backups: 30
  # 日志保留时间
  max-age: 15
  # 是否压缩
  compress: true
  # 控制台日志
  stdout: true
  # 业务日志开关
  enabledbus: true
  # 请求日志开关
  enabledreq: false
  # 数据库日志开关 dev模式，将自动开启
  enableddb: false
  # 自动任务日志开关 dev模式，将自动开启
  enabledjob: false
application:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 服务名称
  name: testApp
  # 服务端口号
  port: 8000
  # 读超时
  read-timeout: 1
  # 写超时
  writer-timeout: 2
  # 加密成本
  encryption-cost: 12
database:
  # 数据库类型 mysql，sqlite3， postgres
  driver: mysql
  # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  source: root:@tcp(127.0.0.1:3306)/os?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
  # 最大空闲连接数
  max-idle-conns: 50
  # 最大打开连接数
  max-open-conns: 200
  # 重用连接的最长时间
  max-life-time: 5
redis:
  # 网络
  network: 'tcp'
  # 地址
  addr: '127.0.0.1:6379'
  # 密码
  password: ''
  # db
  db: 0
jwt:
  # token 密钥，生产环境时及的修改
  secret: 'jwt_test'
  # token 过期时间 单位：秒
  timeout: 60
sms:
  access-key-id: 'xx'
  access-secret: 'xx'
